name: discord-bot CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    # create a zip file with all files required by the module to add to the release
    - run: zip -r ./discord-bot.zip module.json scripts/ lang/ styles/

    # Get the version from 'module.json'
    - name: Get Version
      shell: bash
      id: get-version
      run: echo "version=$(node ./.github/workflows/get-version.js)" >> $GITHUB_OUTPUT

    # Create a release for this specific version
    - name: Create Release
      id: create_version_release
      uses: ncipollo/release-action@v1
      with:
        allowUpdates: true # set this to false if you want to prevent updating existing releases
        name: Release ${{ steps.get-version.outputs.version }}
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./discord-bot.zip'
        tag: ${{ steps.get-version.outputs.version }}

    # Update the 'latest' release
    - name: Create Release
      id: create_latest_release
      uses: ncipollo/release-action@v1
      if: endsWith(github.ref, 'main')
      with:
        allowUpdates: true
        name: Latest
        draft: false
        prerelease: false
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: './module.json,./discord-bot.zip'
        tag: latest
